sonar.projectKey=adamoutler_joplin-server-vector-memory
sonar.organization=adamoutler
sonar.host.url=https://sonarcloud.io
sonar.sources=server/src,client/src,client/public
sonar.tests=server/tests,client/tests,tests
sonar.python.coverage.reportPaths=server/test-results/pytest-cov.xml
sonar.javascript.lcov.reportPaths=client/test-results/lcov.info
